  - name: Add Anydesk PPA
    become: true
    become_user: root
    shell: 
    dest: /etc/apt/trusted.gpg.d/

  - name: Install Google Cloud SDK Repository
    become: true
    apt_repository:
      repo: 'deb [arch=amd64] https://packages.cloud.google.com/apt cloud-sdk main'
      state: present
      filename: google-cloud-sdk


  - name: Installing PPA Apps for Best Desktop Experience
    become: true
    apt:
      name: '{{ item }}'
      install_recommends: yes
      state: present
    loop:
      - anydesk


      
