---
    - name: Installing Base Apps for Developer
      become: true
      apt:
        name: '{{ item }}'
        install_recommends: yes
        state: present
      loop:
        - build-essential
        - default-jdk
        - libssl-dev
        - exuberant-ctags
        - ncurses-term
        - ack-grep
        - silversearcher-ag
        - fontconfig
        - imagemagick
        - libmagickwand-dev
        - software-properties-common
        - vim-gtk3
        - tilix
        - gnome-tweaks
        - postgresql-14
        - postgresql-contrib
        - postgresql-server-dev-14                
        - curl
        - xterm
        - openjfx
        - maven
        - nmap
        - net-tools
        - traceroute
        - git
        - g++
        - cmake
        - libjsoncpp-dev
        - uuid-dev
        - openssl
        - zlib1g-dev
        - rlwrap
        - gawk
        - sqlite
        - libsqlite3-dev
        - m4
        - libncurses5-dev
        - libwxgtk3.0-gtk3-dev
        - libwxgtk-webview3.0-gtk3-dev
        - libgl1-mesa-dev
        - libglu1-mesa-dev
        - libpng-dev
        - libssh-dev
        - unixodbc-dev
        - xsltproc
        - fop
        - libxml2-utils
        - libncurses-dev
        - openjdk-11-jdk
        - automake
        - flameshot
        - clamav
        - clamtk
        - gufw
        - apache2
        - mysql-server
        - autoconf
        - libreadline-dev
        - libyaml-dev
        - libxslt-dev
        - libffi-dev
        - libtool
        - unzip
        - sqlite3
        - libsqlite3-dev
        - gcc
        - zsh
        - neofetch
        - sassc
        - sqlite
        - libsqlite3-dev
        - ubuntu-restricted-extras
        - gnupg
        - ca-certificates
        - python3-dev
        - python3-pip
        - python3-apt
        - pwgen
        - nodejs
        - npm
        - yarn
        - apache2
        - php
        - libapache2-mod-php
        - php-soap
        - php-xml
        - php-curl
        - php-opcache
        - php-gd
        - php-sqlite3
        - php-mbstring
        - phpmyadmin
        - audacity
        - blender
        - clipit
        - darktable
        - inkscape
        - gimp
        - dia
        - geany
        - glade
        - kdenlive
        - openshot-qt
        - wine        
        - winetricks
        - playonlinux
        - preload
        - neovim        
        - fonts-hack            
        - redis-server
        - libhiredis-dev
        - memcached
        - libmemcached-dev                 
        - php-mysql
        - jq
        - mtr        
        - htop
        - ctop        
        - wget
        - ncdu
        - tree
        - apt-transport-https
        - make
        - bash-completion
        - gnupg-agent
        - mlocate
        - gnome-themes-extra
        - gtk2-engines-murrine
        - emacs
        - gcc-multilib
        - g++-multilib
        - llvm
        - llvm-11
        - llvm-12
        - llvm-13
        - clang
        - mingw-w64
        - exa
        - virtualbox-qt
        - virtualbox-ext-pack
        - openssh-server
      when: ansible_distribution == "Ubuntu" and ansible_distribution_version == "22.04"
      ignore_errors: true

    - name: Installing Gstreamer 
      become: true
      apt:
        name: '{{ item }}'
        install_recommends: yes
        state: present
      loop:
        - libgstreamer1.0-dev
        - libgstreamer-plugins-base1.0-dev
        - libgstreamer-plugins-bad1.0-dev
        - gstreamer1.0-plugins-base
        - gstreamer1.0-plugins-good
        - gstreamer1.0-plugins-bad
        - gstreamer1.0-plugins-ugly
        - gstreamer1.0-libav
        - gstreamer1.0-tools
        - gstreamer1.0-x
        - gstreamer1.0-alsa
        - gstreamer1.0-gl
        - gstreamer1.0-gtk3
        - gstreamer1.0-qt5
        - gstreamer1.0-pulseaudio  
      when: ansible_distribution == "Ubuntu" and ansible_distribution_version == "22.04"
      ignore_errors: true
                                                                              


