      - name: Installing Vault 1.8.1
        become: true
        unarchive:
          src: 'https://releases.hashicorp.com/vault/1.8.1/vault_1.8.1_linux_amd64.zip'
          dest: /usr/local/bin
          remote_src: yes

      - name: Installing gomplate 3.9.0
        become: true
        get_url:    
          url: 'https://github.com/hairyhenderson/gomplate/releases/download/v3.9.0/gomplate_linux-amd64'
          dest: /usr/local/bin/gomplate
          mode: 755

      - name: Installing Stern 1.11.0
        become: true
        get_url:    
          url: 'https://github.com/wercker/stern/releases/download/1.11.0/stern_linux_amd64'
          dest: /usr/local/bin/stern
          mode: 755