version: '3.8'

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-CU15-ubuntu-20.04
    ports:
      - 1433:1433
    volumes:
      - ~/apps/mssql/data:/var/lib/mssqlql/data
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${SA_PASSWORD}
      - MSSQL_PID=${MSSQL_PID}